CREATE TABLE
    mst_tax_codes (
        id SERIAL PRIMARY KEY,
        name VARCHAR NOT NULL,
        description VARCHAR NOT NULL,
        type VARCHAR NOT NULL,
        rate FLOAT NOT NULL,
        include_price BOOLEAN NOT NULL DEFAULT FALSE,
        include_discount BOOLEAN NOT NULL DEFAULT FALSE,
        include_restock_fee BOOLEAN NOT NULL DEFAULT FALSE,
        deductible BOOLEAN NOT NULL DEFAULT FALSE,
        include_freight BOOLEAN NOT NULL DEFAULT FALSE,
        include_duty BOOLEAN NOT NULL DEFAULT FALSE,
        include_brokerage BOOLEAN NOT NULL DEFAULT FALSE,
        include_insurance BOOLEAN NOT NULL DEFAULT FALSE,
        include_local_freight BOOLEAN NOT NULL DEFAULT FALSE,
        include_misc BOOLEAN NOT NULL DEFAULT FALSE,
        include_surcharge BOOLEAN NOT NULL DEFAULT FALSE,
        assess_on_return BOOLEAN NOT NULL DEFAULT FALSE,
        include_tax_on_prev_system BOOLEAN NOT NULL DEFAULT FALSE,
        id_account_ar INT REFERENCES mst_chart_of_accounts (id) ON UPDATE CASCADE ON DELETE RESTRICT,
        id_account_ar_process INT REFERENCES mst_chart_of_accounts (id) ON UPDATE CASCADE ON DELETE RESTRICT,
        id_account_ap INT REFERENCES mst_chart_of_accounts (id) ON UPDATE CASCADE ON DELETE RESTRICT,
        id_createdby INT REFERENCES mst_users (id) ON UPDATE CASCADE ON DELETE RESTRICT,
        id_updatedby INT REFERENCES mst_users (id) ON UPDATE CASCADE ON DELETE RESTRICT,
        created_at TIMESTAMPTZ DEFAULT NOW (),
        updated_at TIMESTAMPTZ DEFAULT NOW ()
    );