CREATE TABLE
    mst_machine_details (
        id SERIAL PRIMARY KEY,
        id_machine INT REFERENCES mst_machines (id) ON UPDATE CASCADE ON DELETE RESTRICT,
        rev_no INT,
        code VARCHAR NOT NULL,
        code_old VARCHAR,
        asset_num VARCHAR NOT NULL,
        asset_num_old VARCHAR,
        description VARCHAR NOT NULL,
        name VARCHAR NOT NULL,
        maker VARCHAR NOT NULL,
        power FLOAT NOT NULL,
        id_power_uom INT REFERENCES mst_uoms (id) ON UPDATE CASCADE ON DELETE RESTRICT,
        electricity FLOAT NOT NULL,
        id_electricity_uom INT REFERENCES mst_uoms (id) ON UPDATE CASCADE ON DELETE RESTRICT,
        cavity INT NOT NULL,
        lubricant VARCHAR NOT NULL,
        lubricant_capacity FLOAT NOT NULL,
        id_lubricant_uom INT REFERENCES mst_uoms (id) ON UPDATE CASCADE ON DELETE RESTRICT,
        sliding VARCHAR NOT NULL,
        sliding_capacity FLOAT NOT NULL,
        id_sliding_uom INT REFERENCES mst_uoms (id) ON UPDATE CASCADE ON DELETE RESTRICT,
        coolant VARCHAR NOT NULL,
        coolant_capacity FLOAT NOT NULL,
        id_coolant_uom INT REFERENCES mst_uoms (id) ON UPDATE CASCADE ON DELETE RESTRICT,
        hydraulic VARCHAR NOT NULL,
        hydraulic_capacity FLOAT NOT NULL,
        id_hydraulic_uom INT REFERENCES mst_uoms (id) ON UPDATE CASCADE ON DELETE RESTRICT,
        dimension_front FLOAT NOT NULL,
        id_dimension_front_uom INT REFERENCES mst_uoms (id) ON UPDATE CASCADE ON DELETE RESTRICT,
        dimension_side FLOAT NOT NULL,
        id_dimension_side_uom INT REFERENCES mst_uoms (id) ON UPDATE CASCADE ON DELETE RESTRICT,
        id_createdby INT REFERENCES mst_users (id) ON UPDATE CASCADE ON DELETE RESTRICT,
        id_updatedby INT REFERENCES mst_users (id) ON UPDATE CASCADE ON DELETE RESTRICT,
        created_at TIMESTAMPTZ,
        updated_at TIMESTAMPTZ
    );