CREATE TABLE
    mst_material_details (
        id SERIAL PRIMARY KEY,
        id_material INT REFERENCES mst_materials (id) ON UPDATE CASCADE ON DELETE CASCADE,
        rev_no INT,
        rmss_num VARCHAR NOT NULL,
        od_tolerance_plus FLOAT,
        od_tolerance_min FLOAT,
        id_tolerance_plus FLOAT,
        id_tolerance_min FLOAT,
        width FLOAT,
        height FLOAT,
        ovality VARCHAR,
        cutting_length VARCHAR,
        hardness VARCHAR,
        compotition_c VARCHAR,
        compotition_si VARCHAR,
        compotition_mn VARCHAR,
        compotition_p VARCHAR,
        compotition_s VARCHAR,
        compotition_cu VARCHAR,
        compotition_ni VARCHAR,
        compotition_cr VARCHAR,
        compotition_mo VARCHAR,
        tensile_strength VARCHAR,
        sa_ratio VARCHAR,
        origin VARCHAR,
        remarks VARCHAR,
        id_createdby INT REFERENCES mst_users (id) ON UPDATE CASCADE ON DELETE RESTRICT,
        id_updatedby INT REFERENCES mst_users (id) ON UPDATE CASCADE ON DELETE RESTRICT,
        created_at TIMESTAMPTZ,
        updated_at TIMESTAMPTZ
    );